# Generated by Django 5.1.15 on 2026-08-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="location",
            field=models.CharField(blank=True, max_length=100, verbose_name="location"),
        ),
    ]
