# Generated by Django 5.1.15 on 2026-08-20 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=285, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("festival", "Festival"),
                            ("cultural", "Cultural"),
                            ("religious", "Religious"),
                            ("community", "Community"),
                            ("educational", "Educational"),
                            ("local", "Local Event"),
                        ],
                        default="festival",
                        max_length=50,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="events/covers/"
                    ),
                ),
                (
                    "short_description",
                    models.TextField(help_text="Brief summary shown on listing cards"),
                ),
                (
                    "about",
                    models.TextField(
                        help_text="Full detailed description of the event"
                    ),
                ),
                (
                    "history_background",
                    models.TextField(
                        blank=True, help_text="Historical or cultural significance"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "location",
                    models.CharField(help_text="e.g. Darbhanga, Bihar", max_length=255),
                ),
                (
                    "venue_info",
                    models.TextField(
                        blank=True, help_text="Specific venue address or hall details"
                    ),
                ),
                (
                    "organizer",
                    models.CharField(
                        blank=True, help_text="Organizer or Samiti name", max_length=255
                    ),
                ),
                (
                    "contact_info",
                    models.CharField(
                        blank=True,
                        help_text="Phone number or contact details",
                        max_length=255,
                    ),
                ),
                (
                    "map_location",
                    models.CharField(
                        blank=True,
                        help_text="Google Maps URL or embed query",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("submitter_name", models.CharField(blank=True, max_length=150)),
                ("submitter_email", models.EmailField(blank=True, max_length=254)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event & Festival",
                "verbose_name_plural": "Events & Festivals",
                "ordering": ["start_date", "-is_featured", "title"],
            },
        ),
        migrations.CreateModel(
            name="EventGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="events/gallery/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventImportantDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. Sandhi Puja Timings", max_length=255
                    ),
                ),
                (
                    "date_info",
                    models.CharField(
                        help_text="e.g. 13 Oct, 11:45 PM - 12:33 AM", max_length=255
                    ),
                ),
                ("details", models.CharField(blank=True, max_length=255)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="important_dates",
                        to="events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventScheduleDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.IntegerField(default=1)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. Day 1 — 10 October / Maha Saptami",
                        max_length=255,
                    ),
                ),
                ("morning_program", models.TextField(blank=True)),
                ("afternoon_program", models.TextField(blank=True)),
                ("evening_program", models.TextField(blank=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_days",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["day_number", "date"],
            },
        ),
    ]
