# Generated by Django 5.1.15 on 2026-08-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_portal", "0005_alter_jobapplication_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
    ]
