# Generated by Django 5.1.15 on 2026-08-20 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_news",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="news",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="news",
            name="source_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="news",
            name="source_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="news",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="summary",
            field=models.CharField(
                blank=True, help_text="Short article summary", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="category",
            field=models.CharField(
                choices=[
                    ("MITHILA", "मिथिला"),
                    ("BIHAR", "बिहार"),
                    ("EDUCATION", "शिक्षा"),
                    ("JOBS", "रोजगार"),
                    ("SOCIETY", "समाज"),
                    ("CULTURE", "संस्कृति"),
                    ("POLITICS", "राजनीति"),
                    ("BUSINESS", "व्यापार"),
                    ("SPORTS", "खेल"),
                    ("TECH", "तकनीक"),
                    ("LOCAL", "स्थानीय समाचार"),
                ],
                default="LOCAL",
                max_length=20,
            ),
        ),
    ]
