# Generated by Django 5.1.15 on 2026-08-20 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="MithilaMilan", max_length=150)),
                (
                    "site_tagline",
                    models.CharField(default="जय मिथिला! जय मैथिली!", max_length=255),
                ),
                (
                    "support_email",
                    models.EmailField(
                        default="support@mithilamilan.com", max_length=254
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(default="+91 9876543210", max_length=20),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("allow_registrations", models.BooleanField(default=True)),
                ("require_submission_approval", models.BooleanField(default=True)),
                (
                    "featured_community_slugs",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated community slugs for homepage",
                    ),
                ),
                (
                    "featured_news_ids",
                    models.TextField(blank=True, help_text="Comma-separated news IDs"),
                ),
                (
                    "featured_event_ids",
                    models.TextField(blank=True, help_text="Comma-separated event IDs"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AdminActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=150)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=100)),
                ("details", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Activity Log",
                "verbose_name_plural": "Admin Activity Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
