# Generated by Django 5.1.15 on 2026-08-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_platformsetting_adminactivitylog"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("platform", models.CharField(default="Google Ads", max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("target_audience", models.CharField(blank=True, max_length=255)),
                ("landing_page", models.CharField(default="/", max_length=255)),
                ("utm_source", models.CharField(default="google", max_length=100)),
                ("utm_medium", models.CharField(default="cpc", max_length=100)),
                ("utm_campaign", models.CharField(max_length=100)),
                (
                    "budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Active", "Active"),
                            ("Paused", "Paused"),
                            ("Completed", "Completed"),
                        ],
                        default="Draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RobotsConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        default="User-agent: *\nDisallow: /admin/\nDisallow: /admin-panel/\nDisallow: /users/login/\nDisallow: /users/signup/\n\nSitemap: https://mithilamilan.com/sitemap.xml"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SEOIntegrationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gsc_property_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Search Console Domain Property",
                        max_length=255,
                    ),
                ),
                ("gsc_connected", models.BooleanField(default=False)),
                (
                    "ga4_measurement_id",
                    models.CharField(
                        blank=True, help_text="e.g. G-XXXXXXXXXX", max_length=100
                    ),
                ),
                ("ga4_connected", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SEOPageMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="e.g. / or /news/ or /r/madhubani/",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("focus_keyword", models.CharField(blank=True, max_length=150)),
                ("secondary_keywords", models.CharField(blank=True, max_length=255)),
                ("canonical_url", models.URLField(blank=True)),
                ("og_title", models.CharField(blank=True, max_length=255)),
                ("og_description", models.TextField(blank=True)),
                ("og_image", models.CharField(blank=True, max_length=500)),
                ("robots_index", models.BooleanField(default=True)),
                ("robots_follow", models.BooleanField(default=True)),
                ("schema_type", models.CharField(default="Article", max_length=50)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SEO Page Meta",
                "verbose_name_plural": "SEO Page Metas",
                "ordering": ["path"],
            },
        ),
        migrations.CreateModel(
            name="SocialAccountTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("handle_or_name", models.CharField(max_length=150)),
                ("url", models.URLField()),
                ("followers", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                ("is_connected", models.BooleanField(default=False)),
            ],
        ),
    ]
