# Generated by Django 5.0.2 on 2026-08-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_marketingcampaign_robotsconfig_seointegrationsetting_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="MithilaMilan", max_length=100)),
                (
                    "tagline",
                    models.CharField(
                        default="मिथिला के लोक, संस्कृति आ समाज के एक डिजिटल मंच।",
                        max_length=255,
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        default="MithilaMilan is a community platform created to connect people, culture, businesses, stories, opportunities and information related to Mithila."
                    ),
                ),
                (
                    "subline",
                    models.CharField(default="Made with ❤️ in Mithila", max_length=100),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="contact@mithilamilan.com", max_length=254
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        default="support@mithilamilan.com", max_length=254
                    ),
                ),
                (
                    "report_issue_email",
                    models.EmailField(
                        default="safety@mithilamilan.com", max_length=254
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True, default="https://facebook.com/mithilamilan"
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, default="https://instagram.com/mithilamilan"
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(
                        blank=True, default="https://youtube.com/@mithilamilan"
                    ),
                ),
                (
                    "x_twitter_url",
                    models.URLField(blank=True, default="https://x.com/mithilamilan"),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True, default="https://linkedin.com/company/mithilamilan"
                    ),
                ),
                (
                    "copyright_text",
                    models.CharField(
                        default="© 2026 MithilaMilan. All rights reserved.",
                        max_length=255,
                    ),
                ),
                (
                    "platform_disclaimer",
                    models.TextField(
                        default="Important: MithilaMilan is a community and information platform. Content, listings, advertisements, products, services, events, jobs, rentals and other information may be submitted or provided by users, businesses, organizers or third parties. MithilaMilan does not automatically endorse or guarantee every third-party listing or claim.\n\nMithilaMilan is not responsible for fraudulent, misleading, unauthorized or unlawful activities carried out by third parties through information, listings, posts, advertisements, transactions or communications on the platform, subject to applicable law.\n\nUsers are responsible for verifying information, identities, offers, prices, payment details and other claims before entering into any transaction or agreement."
                    ),
                ),
                (
                    "fraud_warning_title",
                    models.CharField(default="⚠️ Stay Safe", max_length=100),
                ),
                (
                    "fraud_warning_text",
                    models.TextField(
                        default="Never share your OTP, password, PIN, card details or other sensitive information with anyone claiming to represent MithilaMilan.\n\nMithilaMilan will never ask you to transfer money to a personal account for verification or account activation.\n\nIf you notice suspicious activity, report it to us through the platform."
                    ),
                ),
                (
                    "user_content_disclaimer",
                    models.TextField(
                        default="User-generated content belongs to its respective authors. Users are responsible for the content they submit. MithilaMilan may review, moderate, restrict or remove content that violates applicable laws, platform policies or community guidelines."
                    ),
                ),
                (
                    "marketplace_disclaimer",
                    models.TextField(
                        default="Products and services listed by independent sellers or providers may be subject to separate seller terms, availability, pricing, delivery and return conditions. Users should review the applicable details before purchasing."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Footer & Platform Settings",
                "verbose_name_plural": "Footer & Platform Settings",
            },
        ),
        migrations.CreateModel(
            name="LegalPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("terms", "Terms of Service"),
                            ("privacy", "Privacy Policy"),
                            ("cancellation", "Cancellation Policy"),
                            ("community-guidelines", "Community Guidelines"),
                            ("content-policy", "Content Policy"),
                            ("refund-policy", "Refund Policy"),
                            ("disclaimer", "Disclaimer"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.CharField(blank=True, max_length=300)),
                (
                    "content",
                    models.TextField(help_text="HTML or Markdown legal text content"),
                ),
                ("last_updated", models.DateField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Legal Page",
                "verbose_name_plural": "Legal Pages",
                "ordering": ["title"],
            },
        ),
    ]
