# Generated by Django 5.1.15 on 2026-08-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pg_rental", "0005_booking_mobile_booking_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="pglisting",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
    ]
