# Generated by Django 5.1.15 on 2026-08-20 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PanditProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("pandit", "Pandit"),
                            ("astrologer", "Astrologer"),
                            ("both", "Pandit & Astrologer"),
                        ],
                        default="pandit",
                        max_length=20,
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="pandits/profiles/"
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        help_text="e.g. Senior Vedic Scholar & Karma Kanda Specialist",
                        max_length=255,
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        help_text="Mandatory. Include country code if outside India e.g. 9876543210",
                        max_length=20,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "location",
                    models.CharField(help_text="e.g. Darbhanga, Bihar", max_length=255),
                ),
                (
                    "address_area",
                    models.TextField(
                        blank=True, help_text="Local area or full address details"
                    ),
                ),
                (
                    "experience_years",
                    models.IntegerField(default=5, help_text="Years of experience"),
                ),
                (
                    "languages",
                    models.CharField(
                        help_text="e.g. Maithili, Hindi, Sanskrit, English",
                        max_length=255,
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        help_text="e.g. Griha Pravesh, Vivah, Kundali Reading, Vastu",
                        max_length=255,
                    ),
                ),
                (
                    "services_offered",
                    models.TextField(
                        help_text="Detailed list or bullet points of rituals, pujas or horoscopes offered"
                    ),
                ),
                (
                    "about",
                    models.TextField(help_text="Professional summary and background"),
                ),
                (
                    "availability",
                    models.CharField(
                        default="Mon - Sun: 8:00 AM - 8:00 PM", max_length=255
                    ),
                ),
                (
                    "service_pricing",
                    models.TextField(
                        blank=True,
                        help_text="Optional pricing details e.g. Kundali Reading: ₹501",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Shows Verified Badge on profile"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pandit_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pandit & Astrologer Profile",
                "verbose_name_plural": "Pandit & Astrologer Profiles",
                "ordering": [
                    "-is_featured",
                    "-is_verified",
                    "-experience_years",
                    "full_name",
                ],
            },
        ),
        migrations.CreateModel(
            name="PanditGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="pandits/gallery/")),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="pandits.panditprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsultationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=150)),
                ("user_phone", models.CharField(max_length=20)),
                ("user_whatsapp", models.CharField(blank=True, max_length=20)),
                ("service_required", models.CharField(max_length=255)),
                ("preferred_date", models.DateField()),
                ("preferred_time", models.CharField(blank=True, max_length=100)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("offline", "In-Person / At Home"),
                            ("online", "Online / Video Consultation"),
                        ],
                        default="offline",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Response"),
                            ("contacted", "Contacted"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation_requests",
                        to="pandits.panditprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
