# Generated by Django 5.1.15 on 2026-08-20 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MithilaPride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=285, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("scholar", "Scholar"),
                            ("educator", "Educator"),
                            ("artist", "Artist"),
                            ("writer", "Writer"),
                            ("researcher", "Researcher"),
                            ("cultural_personality", "Cultural Personality"),
                            ("teacher", "Teacher"),
                            ("author", "Author"),
                            ("other", "Other Contributor"),
                        ],
                        default="scholar",
                        max_length=50,
                    ),
                ),
                (
                    "era_generation",
                    models.CharField(
                        choices=[
                            ("classical", "Classical & Ancient Era"),
                            ("20th_century", "20th Century Pioneers"),
                            ("contemporary", "Contemporary Leaders"),
                        ],
                        default="contemporary",
                        max_length=50,
                    ),
                ),
                (
                    "place_location",
                    models.CharField(
                        help_text="Native place, e.g. Madhubani / Darbhanga, Bihar",
                        max_length=255,
                    ),
                ),
                (
                    "photograph",
                    models.ImageField(
                        blank=True, null=True, upload_to="mithila_pride/photos/"
                    ),
                ),
                (
                    "biography",
                    models.TextField(
                        help_text="Overview biography and summary of life"
                    ),
                ),
                (
                    "early_life",
                    models.TextField(
                        blank=True, help_text="Birth, childhood, and roots"
                    ),
                ),
                (
                    "education",
                    models.TextField(
                        blank=True, help_text="Academic qualifications, institutions"
                    ),
                ),
                (
                    "career",
                    models.TextField(
                        blank=True, help_text="Professional career trajectory"
                    ),
                ),
                (
                    "major_achievements",
                    models.TextField(
                        blank=True, help_text="Key achievements and milestones"
                    ),
                ),
                (
                    "awards",
                    models.TextField(
                        blank=True,
                        help_text="Honors, Padma awards, Sahitya Akademi, etc.",
                    ),
                ),
                (
                    "publications_work",
                    models.TextField(
                        blank=True,
                        help_text="Notable books, papers, artwork, or compositions",
                    ),
                ),
                (
                    "contributions_to_mithila",
                    models.TextField(
                        help_text="Key contributions to Mithila language, culture, society or research"
                    ),
                ),
                (
                    "organization_institution",
                    models.CharField(
                        blank=True,
                        help_text="University, academy, or organization associated",
                        max_length=255,
                    ),
                ),
                (
                    "website_social_links",
                    models.TextField(
                        blank=True,
                        help_text="Wikipedia link, official website, or news profiles",
                    ),
                ),
                (
                    "references_sources",
                    models.TextField(
                        blank=True, help_text="Citations or reference sources"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("submitter_name", models.CharField(blank=True, max_length=150)),
                ("submitter_email", models.EmailField(blank=True, max_length=254)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_personalities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mithila Pride & Scholar",
                "verbose_name_plural": "Mithila Pride & Scholars",
                "ordering": ["-is_featured", "full_name"],
            },
        ),
        migrations.CreateModel(
            name="MithilaPrideGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="mithila_pride/gallery/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="mithila_pride.mithilapride",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MithilaPrideTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_or_date",
                    models.CharField(
                        help_text="e.g. 1974 or 15 August 1985", max_length=100
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="mithila_pride.mithilapride",
                    ),
                ),
            ],
            options={
                "ordering": ["year_or_date"],
            },
        ),
    ]
