# Generated by Django 5.1.15 on 2026-08-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lost_and_found", "0002_lostandfounditem_is_resolved"),
    ]

    operations = [
        migrations.AddField(
            model_name="lostandfounditem",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
    ]
