# Generated by Django 5.1.15 on 2026-08-20 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="cab_auto/drivers/"
                    ),
                ),
                ("age", models.IntegerField(default=30)),
                ("mobile_number", models.CharField(max_length=20)),
                (
                    "whatsapp_number",
                    models.CharField(
                        help_text="Mandatory WhatsApp number", max_length=20
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("auto", "Auto / E-Rickshaw"), ("taxi", "Taxi / Cab")],
                        default="auto",
                        max_length=20,
                    ),
                ),
                (
                    "vehicle_model",
                    models.CharField(
                        help_text="e.g. Bajaj RE Maxima / Swift Dzire AC",
                        max_length=150,
                    ),
                ),
                (
                    "vehicle_number",
                    models.CharField(
                        blank=True,
                        help_text="Registration Number (Optional)",
                        max_length=50,
                    ),
                ),
                (
                    "service_area",
                    models.CharField(
                        help_text="e.g. Darbhanga Railway Station, Airport, Madhubani Local",
                        max_length=255,
                    ),
                ),
                ("experience_years", models.IntegerField(default=5)),
                (
                    "available_hours",
                    models.CharField(default="24/7 Available", max_length=150),
                ),
                (
                    "about",
                    models.TextField(
                        blank=True, help_text="Short background or routes covered"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                            ("published", "Published"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="driver_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cab & Auto Driver Profile",
                "verbose_name_plural": "Cab & Auto Driver Profiles",
                "ordering": ["-is_featured", "-is_verified", "full_name"],
            },
        ),
    ]
