# Generated by Django 5.1.15 on 2026-08-20 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatrimonialProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "looking_for",
                    models.CharField(
                        choices=[
                            ("son", "Suitable Match for Son"),
                            ("daughter", "Suitable Match for Daughter"),
                            ("other", "Suitable Match for Relative"),
                        ],
                        default="son",
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Groom / Male"),
                            ("female", "Bride / Female"),
                        ],
                        default="male",
                        max_length=10,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(help_text="Candidate Name", max_length=150),
                ),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("age", models.IntegerField(default=25)),
                (
                    "height",
                    models.CharField(
                        blank=True, help_text="e.g. 5' 8\" (Optional)", max_length=50
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        help_text="e.g. B.Tech (IIT), MBA / M.A. Sanskrit",
                        max_length=255,
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        help_text="e.g. Senior Software Engineer at MNC / Govt Officer",
                        max_length=255,
                    ),
                ),
                (
                    "location",
                    models.CharField(help_text="e.g. Delhi NCR", max_length=255),
                ),
                (
                    "native_place",
                    models.CharField(
                        help_text="e.g. Madhubani / Darbhanga, Bihar", max_length=255
                    ),
                ),
                (
                    "current_city",
                    models.CharField(
                        help_text="e.g. Noida / New Delhi / Bangalore", max_length=255
                    ),
                ),
                (
                    "community_family_details",
                    models.TextField(
                        blank=True,
                        help_text="Family lineage or gotra background (Optional)",
                    ),
                ),
                (
                    "about_person",
                    models.TextField(
                        help_text="Overview of personality, hobbies, background"
                    ),
                ),
                (
                    "family_info",
                    models.TextField(
                        help_text="Father's profession, mother, siblings, background"
                    ),
                ),
                (
                    "expectations",
                    models.TextField(
                        help_text="Partner preferences and family expectations"
                    ),
                ),
                (
                    "contact_person_name",
                    models.CharField(
                        help_text="Parent or guardian name", max_length=150
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        help_text="Mandatory WhatsApp number for private contact button",
                        max_length=20,
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="ghatkaiti/photos/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matrimonial_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ghatkaiti Matrimonial Profile",
                "verbose_name_plural": "Ghatkaiti Matrimonial Profiles",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfileReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reporter_name", models.CharField(blank=True, max_length=150)),
                ("reporter_email", models.EmailField(blank=True, max_length=254)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("misleading", "Misleading Information"),
                            ("fake_profile", "Fake Profile"),
                            ("inappropriate", "Inappropriate Content"),
                            ("other", "Other Reason"),
                        ],
                        default="misleading",
                        max_length=50,
                    ),
                ),
                ("details", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="ghatkaiti.matrimonialprofile",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
