# Generated by Django 5.1.15 on 2026-08-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storytelling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="excerpt",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="story",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="story",
            name="category",
            field=models.CharField(
                choices=[
                    ("MITHILA", "मिथिला"),
                    ("FOLKLORE", "लोककथा"),
                    ("MEMOIR", "संस्मरण"),
                    ("CULTURE", "संस्कृति"),
                    ("TRAVEL", "यात्रा"),
                    ("PEOPLE", "व्यक्ति"),
                    ("VILLAGE", "गाँव"),
                    ("HISTORY", "इतिहास"),
                    ("INSPIRATIONAL", "प्रेरणादायक"),
                    ("OTHER", "अन्य"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
