# Generated by Django 5.1.15 on 2026-08-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storytelling", "0002_story_excerpt_story_rejection_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="source_name",
            field=models.CharField(
                blank=True,
                help_text="e.g. Sahitya Akademi / Mithila Folk Literature",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="source_url",
            field=models.URLField(
                blank=True, help_text="Verified reference link", max_length=500
            ),
        ),
    ]
