# Generated by Django 5.1.15 on 2026-08-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delhi_wiki", "0008_add_metro_stations"),
    ]

    operations = [
        migrations.AddField(
            model_name="landmark",
            name="source_name",
            field=models.CharField(
                blank=True,
                help_text="e.g. Madhubani District Website / Govt of Bihar Tourism",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="landmark",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="Official verification source link",
                max_length=500,
            ),
        ),
    ]
