# Generated by Django 5.1.15 on 2026-08-20 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MuhuratCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_hi", models.CharField(max_length=100)),
                ("name_mai", models.CharField(blank=True, max_length=100)),
                ("name_en", models.CharField(blank=True, max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "icon",
                    models.CharField(
                        default="fa-calendar-check",
                        help_text="FontAwesome class e.g. fa-ring, fa-scissors, fa-om",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                "ordering": ["order", "name_hi"],
            },
        ),
        migrations.CreateModel(
            name="PanchangSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="मैथिली पंचांग (उर्वशी प्रकाशन)", max_length=255
                    ),
                ),
                (
                    "year_label",
                    models.CharField(
                        default="२०२६ - २०२७ ई० (१४३४ साल)", max_length=100
                    ),
                ),
                (
                    "publisher",
                    models.CharField(default="उर्वशी प्रकाशन, पटना", max_length=255),
                ),
                (
                    "editor",
                    models.CharField(
                        default="पं० सचिदानन्द झा (गणित, फलित)", max_length=255
                    ),
                ),
                (
                    "compiler",
                    models.CharField(default="पं० गोपीकान्त झा", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="मिथिलादेशीय मकरन्दानुसार मैथिली पंचांग"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PanchangYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gregorian_year",
                    models.IntegerField(
                        default=2026, help_text="Starting Gregorian Year"
                    ),
                ),
                (
                    "title_hi",
                    models.CharField(
                        default="सन १४३४ साल (अंग्रेजी २०२६ - २०२७ ई०)", max_length=255
                    ),
                ),
                ("vikram_samvat", models.CharField(default="२०८३-८४", max_length=100)),
                ("saka_samvat", models.CharField(default="१९४८", max_length=100)),
                ("king_planet", models.CharField(default="शनि", max_length=100)),
                ("minister_planet", models.CharField(default="मंगल", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PanchangAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_type", models.CharField(max_length=100)),
                ("record_id", models.PositiveIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created Record"),
                            ("UPDATE", "Updated Record"),
                            ("VERIFY", "Verified Record"),
                            ("PUBLISH", "Published Record"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.TextField()),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PanchangMonth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_hi", models.CharField(max_length=100)),
                ("name_mai", models.CharField(blank=True, max_length=100)),
                ("name_en", models.CharField(max_length=100)),
                ("month_order", models.PositiveSmallIntegerField(help_text="1 to 12")),
                (
                    "gregorian_range_hi",
                    models.CharField(help_text="e.g. जुलाई – अगस्त", max_length=100),
                ),
                (
                    "gregorian_range_en",
                    models.CharField(help_text="e.g. July – August", max_length=100),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="months",
                        to="mithila_panchang.panchangyear",
                    ),
                ),
            ],
            options={
                "ordering": ["month_order"],
            },
        ),
        migrations.CreateModel(
            name="ScannedPanchangPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.PositiveIntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "image_path",
                    models.CharField(
                        help_text="Path to scanned page image, e.g. panch_ocr/page-02.jpg",
                        max_length=255,
                    ),
                ),
                ("ocr_text", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scanned_pages",
                        to="mithila_panchang.panchangsource",
                    ),
                ),
            ],
            options={
                "ordering": ["page_number"],
            },
        ),
        migrations.CreateModel(
            name="PanchangDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("mithila_month_name", models.CharField(blank=True, max_length=100)),
                (
                    "mithila_tithi_name",
                    models.CharField(default="प्रतिपदा", max_length=100),
                ),
                (
                    "paksha",
                    models.CharField(
                        choices=[("शुक्ल", "शुक्ल पक्ष"), ("कृष्ण", "कृष्ण पक्ष")],
                        default="शुक्ल",
                        max_length=50,
                    ),
                ),
                (
                    "tithi_end_time",
                    models.CharField(
                        blank=True,
                        help_text="e.g. रा. ०९।४९ या 09:49 PM",
                        max_length=100,
                    ),
                ),
                ("nakshatra_name", models.CharField(default="रोहिणी", max_length=100)),
                ("nakshatra_end_time", models.CharField(blank=True, max_length=100)),
                (
                    "yoga_name",
                    models.CharField(blank=True, default="सिद्ध", max_length=100),
                ),
                (
                    "karana_name",
                    models.CharField(blank=True, default="बव", max_length=100),
                ),
                ("weekday_name", models.CharField(default="बुधवार", max_length=50)),
                ("sunrise", models.CharField(default="05:30 AM", max_length=50)),
                ("sunset", models.CharField(default="06:45 PM", max_length=50)),
                ("moonrise", models.CharField(default="07:15 PM", max_length=50)),
                ("moonset", models.CharField(default="06:10 AM", max_length=50)),
                ("sun_rashi", models.CharField(default="सिंह", max_length=100)),
                ("moon_rashi", models.CharField(default="कन्या", max_length=100)),
                (
                    "abhijit_muhurta",
                    models.CharField(default="11:48 AM – 12:40 PM", max_length=100),
                ),
                (
                    "rahukaal",
                    models.CharField(default="12:20 PM – 01:55 PM", max_length=100),
                ),
                (
                    "yamaganda",
                    models.CharField(default="07:10 AM – 08:45 AM", max_length=100),
                ),
                (
                    "gulika",
                    models.CharField(default="10:30 AM – 12:00 PM", max_length=100),
                ),
                ("is_amavasya", models.BooleanField(default=False)),
                ("is_purnima", models.BooleanField(default=False)),
                (
                    "special_observances",
                    models.TextField(
                        blank=True,
                        help_text="Special vrat, festival, or notes for the day",
                    ),
                ),
                (
                    "mithila_month",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="days",
                        to="mithila_panchang.panchangmonth",
                    ),
                ),
                (
                    "source_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mithila_panchang.scannedpanchangpage",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="MuhuratDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gregorian_date", models.DateField()),
                ("mithila_month_name", models.CharField(blank=True, max_length=100)),
                (
                    "paksha",
                    models.CharField(
                        blank=True, help_text="e.g. कृष्ण, शुक्ल", max_length=50
                    ),
                ),
                (
                    "tithi_name",
                    models.CharField(
                        blank=True, help_text="e.g. प्रतिपदा, द्वितीया", max_length=100
                    ),
                ),
                (
                    "weekday_name",
                    models.CharField(
                        blank=True, help_text="e.g. बुधवार, शुक्रवार", max_length=50
                    ),
                ),
                (
                    "nakshatra_name",
                    models.CharField(
                        blank=True, help_text="e.g. रोहिणी, हस्त", max_length=100
                    ),
                ),
                (
                    "start_time",
                    models.CharField(
                        blank=True,
                        help_text="Optional clock time string e.g. 06:30 AM",
                        max_length=100,
                    ),
                ),
                (
                    "end_time",
                    models.CharField(
                        blank=True, help_text="Optional end time string", max_length=100
                    ),
                ),
                (
                    "is_full_day_muhurat",
                    models.BooleanField(
                        default=True,
                        help_text="True if exact clock time is not provided by source (shows 'विवाहक दिन' / full day)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Source notes, e.g. (छ०), (क्ष०वै०), दिवा/रात्र",
                    ),
                ),
                (
                    "source_reference_text",
                    models.CharField(default="मैथिली पंचांग, पृष्ठ २", max_length=255),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("NEEDS_REVIEW", "Needs Review"),
                            ("VERIFIED", "Verified"),
                            ("PUBLISHED", "Published"),
                        ],
                        default="PUBLISHED",
                        max_length=30,
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="muhurat_dates",
                        to="mithila_panchang.muhuratcategory",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entered_muhurats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_muhurats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mithila_month",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mithila_panchang.panchangmonth",
                    ),
                ),
                (
                    "source_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mithila_panchang.scannedpanchangpage",
                    ),
                ),
            ],
            options={
                "ordering": ["gregorian_date"],
            },
        ),
        migrations.CreateModel(
            name="Festival",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_hi", models.CharField(max_length=200)),
                ("title_mai", models.CharField(blank=True, max_length=200)),
                ("title_en", models.CharField(blank=True, max_length=200)),
                ("date", models.DateField()),
                ("mithila_month_name", models.CharField(blank=True, max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pabni_tihar", "पाबनि-तिहार (Pabni-Tihar)"),
                            ("vrat", "व्रत (Vrat)"),
                            ("puja", "पूजा (Puja)"),
                            ("mithila_special", "मिथिला विशेष (Mithila Special)"),
                            ("religious", "धार्मिक (Religious)"),
                            ("cultural", "सांस्कृतिक (Cultural)"),
                        ],
                        default="pabni_tihar",
                        max_length=50,
                    ),
                ),
                ("short_description", models.TextField()),
                ("traditions", models.TextField(blank=True)),
                ("puja_vrat_info", models.TextField(blank=True)),
                (
                    "related_event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Connect to existing Events & Festivals entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.event",
                    ),
                ),
                (
                    "mithila_month",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mithila_panchang.panchangmonth",
                    ),
                ),
                (
                    "source_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mithila_panchang.scannedpanchangpage",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
