# Generated by Django 5.1.15 on 2026-08-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mithila_panchang", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MithilaSong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_id",
                    models.CharField(
                        help_text="YouTube Video ID e.g. H501incNC74",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "singer",
                    models.CharField(
                        blank=True, help_text="Singer / Channel Name", max_length=255
                    ),
                ),
                (
                    "category",
                    models.CharField(default="पारम्परिक मैथिली गीत", max_length=100),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                ("is_featured", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
