# Generated by Django 5.1.15 on 2026-08-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mithila_panchang", "0002_mithilasong"),
    ]

    operations = [
        migrations.AddField(
            model_name="mithilasong",
            name="audio_url",
            field=models.CharField(
                blank=True,
                help_text="Direct MP3 Audio URL if available",
                max_length=500,
            ),
        ),
    ]
